name: Check pnpm Lockfile

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "web/**"
  push:
    branches: [main, develop]
    paths:
      - "web/**"

jobs:
  check-pnpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for package-lock.json in web directory
        run: |
          if [ -f "web/package-lock.json" ]; then
            echo "::error:: package-lock.json found in web directory. Please use pnpm instead of npm."
            exit 1
          fi

      - name: Check for pnpm-lock.yaml in web directory
        run: |
          if [ ! -f "web/pnpm-lock.yaml" ]; then
            echo "::error:: pnpm-lock.yaml not found in web directory. Please run 'pnpm install' in the web directory to generate it."
            exit 1
          fi
