name: PNPM Check and ESLint for Web Directory

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "web/**"
  push:
    branches: [main, develop]
    paths:
      - "web/**"

jobs:
  check-pnpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Enable Corepack (Ensures PNPM is Used)
        run: corepack enable

      - name: Verify pnpm version
        run: pnpm --version

      - name: Check for package-lock.json in web directory
        run: |
          if [ -f "web/package-lock.json" ]; then
            echo "::error:: package-lock.json found in web directory. Please use pnpm instead of npm."
            exit 1
          fi

      - name: Check for pnpm-lock.yaml in web directory
        run: |
          if [ ! -f "web/pnpm-lock.yaml" ]; then
            echo "::error:: pnpm-lock.yaml not found in web directory. Please run 'pnpm install' in the web directory to generate it."
            exit 1
          fi

      - name: Install Dependencies in web Directory
        run: |
          cd web
          pnpm install --frozen-lockfile

      - name: Check for outdated dependencies (informational only)
        if: always()
        continue-on-error: true
        run: |
          cd web
          echo "## Checking for outdated dependencies"
          pnpm outdated || true

      - name: Run Lint in web Directory
        run: |
          cd web
          pnpm lint

      - name: Run Build in web Directory
        run: |
          cd web
          pnpm build
